# Generated by Django 2.2 on 2020-07-11 12:20

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20200711_0859'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='job',
            managers=[
                ('jobs', django.db.models.manager.Manager()),
            ],
        ),
    ]
