# Generated by Django 2.2 on 2020-07-11 12:29

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20200711_1220'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='job',
            managers=[
                ('people', django.db.models.manager.Manager()),
            ],
        ),
    ]
