# Generated by Django 2.2 on 2020-07-11 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_auto_20200711_1229'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='job',
            managers=[
            ],
        ),
    ]
